### ISSUE TITLE
In a CSV input file, more data fields than columns causes batch job to hang

### ISSUE THREAD

**Issue by mraross** [bcgov/cpf#42]
The following csv data causes a batch job to get stuck at the Creating Requests state:

`yourId,addressString,expectedMatchPrecision,expectedFullAddress,expectedFaults,exampleNeeded,parcelPoint`
`NonCivicAddressWithKnownSiteNameAndMissingStreet,"Centennial Candle -- Victoria, BC",SITE,"Centennial Candle -- Laurel Lane, Victoria, BC",[STREET_NAME.missing:10,STREET_TYPE.missing:6],F,`

**Comment by pauldaustin** [comment]
Please look at the CPF log files and include the stack trace at the time of the failed request in the ticket.

Paul Austin
President/CEO
Revolution Systems Inc.

+1 (604) 288-4304
paul.austin@revolsys.com
www.revolsys.com

**Comment by mraross** [comment]
Will do.

**Comment by mraross** [comment]
2016-10-17 11:21:37,760	ERROR	ca.bc.gov.open.cpf.api.scheduler.JobPreProcessTask	Error pre-processing job 6194
java.lang.StringIndexOutOfBoundsException: String index out of range: 5
	at java.lang.AbstractStringBuilder.substring(AbstractStringBuilder.java:906)
	at java.lang.StringBuilder.substring(StringBuilder.java:76)
	at java.lang.AbstractStringBuilder.subSequence(AbstractStringBuilder.java:885)
	at java.lang.StringBuilder.subSequence(StringBuilder.java:76)
	at ca.bc.gov.open.cpf.plugin.api.GeometryFactory.hasText(GeometryFactory.java:519)
	at ca.bc.gov.open.cpf.plugin.api.GeometryFactory.parseGeometry(GeometryFactory.java:656)
	at ca.bc.gov.open.cpf.plugin.api.GeometryFactory.createGeometry(GeometryFactory.java:255)
	at ca.bc.gov.open.cpf.plugin.impl.geometry.JtsGeometryDataType.toObjectDo(JtsGeometryDataType.java:40)
	at com.revolsys.datatype.AbstractDataType.toObject(AbstractDataType.java:111)
	at com.revolsys.record.io.MapReaderRecordReader.next(MapReaderRecordReader.java:64)
	at com.revolsys.record.io.MapReaderRecordReader.next(MapReaderRecordReader.java:15)
	at ca.bc.gov.open.cpf.api.scheduler.JobPreProcessTask.process(JobPreProcessTask.java:243)
	at ca.bc.gov.open.cpf.api.scheduler.BatchJobService.preProcessBatchJob(BatchJobService.java:1228)
	at ca.bc.gov.open.cpf.api.scheduler.BatchJobPreProcess.processJob(BatchJobPreProcess.java:53)
	at ca.bc.gov.open.cpf.api.scheduler.AbstractBatchJobChannelProcess.lambda$schedule$0(AbstractBatchJobChannelProcess.java:191)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at com.revolsys.logging.LoggingRunnable.run(LoggingRunnable.java:13)
	at java.lang.Thread.run(Thread.java:745)
2016-10-17 11:21:38,382	ERROR	java.util.concurrent.ThreadPoolExecutor$Worker	Unable to save result data
java.lang.RuntimeException: Unable to save result data
	at ca.bc.gov.open.cpf.api.scheduler.BatchJobService.newBatchJobResult(BatchJobService.java:911)
	at ca.bc.gov.open.cpf.api.scheduler.JobPreProcessTask.addJobValidationError(JobPreProcessTask.java:117)
	at ca.bc.gov.open.cpf.api.scheduler.JobPreProcessTask.process(JobPreProcessTask.java:295)
	at ca.bc.gov.open.cpf.api.scheduler.BatchJobService.preProcessBatchJob(BatchJobService.java:1228)
	at ca.bc.gov.open.cpf.api.scheduler.BatchJobPreProcess.processJob(BatchJobPreProcess.java:53)
	at ca.bc.gov.open.cpf.api.scheduler.AbstractBatchJobChannelProcess.lambda$schedule$0(AbstractBatchJobChannelProcess.java:191)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at com.revolsys.logging.LoggingRunnable.run(LoggingRunnable.java:13)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Unable to create file
	at ca.bc.gov.open.cpf.api.web.controller.DatabaseJobController.newJobFile(DatabaseJobController.java:183)
	at ca.bc.gov.open.cpf.api.web.controller.AbstractJobController.setJobResult(AbstractJobController.java:147)
	at ca.bc.gov.open.cpf.api.scheduler.BatchJobService.newBatchJobResult(BatchJobService.java:908)
	... 9 more
Caused by: org.springframework.dao.DataIntegrityViolationException: Process Batch; SQL [BEGIN insert  into CPF.CPF_BATCH_JOB_FILES (BATCH_JOB_ID, FILE_TYPE, SEQUENCE_NUMBER, CONTENT_TYPE, DATA, WHEN_CREATED) VALUES (?, ?, ?, ?, ?, ?);END;]; ORA-01400: cannot insert NULL into ("CPF"."CPF_BATCH_JOB_FILES"."DATA")
ORA-06512: at line 1
; nested exception is java.sql.SQLIntegrityConstraintViolationException: ORA-01400: cannot insert NULL into ("CPF"."CPF_BATCH_JOB_FILES"."DATA")
ORA-06512: at line 1

	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:243)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)
	at com.revolsys.jdbc.JdbcConnection.getException(JdbcConnection.java:180)
	at com.revolsys.jdbc.io.JdbcWriterImpl.processCurrentBatch(JdbcWriterImpl.java:580)
	at com.revolsys.jdbc.io.JdbcWriterImpl.insert(JdbcWriterImpl.java:512)
	at com.revolsys.jdbc.io.JdbcWriterImpl.insert(JdbcWriterImpl.java:475)
	at com.revolsys.jdbc.io.JdbcWriterImpl.write(JdbcWriterImpl.java:692)
	at com.revolsys.jdbc.io.JdbcWriterImpl.write(JdbcWriterImpl.java:33)
	at com.revolsys.jdbc.io.JdbcWriterWrapper.write(JdbcWriterWrapper.java:67)
	at com.revolsys.jdbc.io.JdbcWriterWrapper.write(JdbcWriterWrapper.java:7)
	at ca.bc.gov.open.cpf.api.domain.CpfDataAccessObject.write(CpfDataAccessObject.java:938)
	at ca.bc.gov.open.cpf.api.domain.CpfDataAccessObject.write(CpfDataAccessObject.java:910)
	at ca.bc.gov.open.cpf.api.web.controller.DatabaseJobController.newJobFile(DatabaseJobController.java:181)
	... 11 more
Caused by: java.sql.SQLIntegrityConstraintViolationException: ORA-01400: cannot insert NULL into ("CPF"."CPF_BATCH_JOB_FILES"."DATA")
ORA-06512: at line 1

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:445)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:396)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:879)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:450)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:192)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:531)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:207)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:1044)
	at oracle.jdbc.driver.OraclePreparedStatement.executeForRowsWithTimeout(OraclePreparedStatement.java:10143)
	at oracle.jdbc.driver.OraclePreparedStatement.executeBatch(OraclePreparedStatement.java:10249)
	at oracle.jdbc.driver.OracleStatementWrapper.executeBatch(OracleStatementWrapper.java:230)
	at org.apache.commons.dbcp2.DelegatingStatement.executeBatch(DelegatingStatement.java:345)
	at org.apache.commons.dbcp2.DelegatingStatement.executeBatch(DelegatingStatement.java:345)
	at com.revolsys.jdbc.io.JdbcWriterImpl.processCurrentBatch(JdbcWriterImpl.java:578)
	... 20 more
2016-10-17 13:24:54,348	ERROR	ca.bc.gov.open.cpf.api.scheduler.JobPreProcessTask	Error pre-processing job 6214
java.lang.StringIndexOutOfBoundsException: String index out of range: 5
	at java.lang.AbstractStringBuilder.substring(AbstractStringBuilder.java:906)
	at java.lang.StringBuilder.substring(StringBuilder.java:76)
	at java.lang.AbstractStringBuilder.subSequence(AbstractStringBuilder.java:885)
	at java.lang.StringBuilder.subSequence(StringBuilder.java:76)
	at ca.bc.gov.open.cpf.plugin.api.GeometryFactory.hasText(GeometryFactory.java:519)
	at ca.bc.gov.open.cpf.plugin.api.GeometryFactory.parseGeometry(GeometryFactory.java:656)
	at ca.bc.gov.open.cpf.plugin.api.GeometryFactory.createGeometry(GeometryFactory.java:255)
	at ca.bc.gov.open.cpf.plugin.impl.geometry.JtsGeometryDataType.toObjectDo(JtsGeometryDataType.java:40)
	at com.revolsys.datatype.AbstractDataType.toObject(AbstractDataType.java:111)
	at com.revolsys.record.io.MapReaderRecordReader.next(MapReaderRecordReader.java:64)
	at com.revolsys.record.io.MapReaderRecordReader.next(MapReaderRecordReader.java:15)
	at ca.bc.gov.open.cpf.api.scheduler.JobPreProcessTask.process(JobPreProcessTask.java:243)
	at ca.bc.gov.open.cpf.api.scheduler.BatchJobService.preProcessBatchJob(BatchJobService.java:1228)
	at ca.bc.gov.open.cpf.api.scheduler.BatchJobPreProcess.processJob(BatchJobPreProcess.java:53)
	at ca.bc.gov.open.cpf.api.scheduler.AbstractBatchJobChannelProcess.lambda$schedule$0(AbstractBatchJobChannelProcess.java:191)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at com.revolsys.logging.LoggingRunnable.run(LoggingRunnable.java:13)
	at java.lang.Thread.run(Thread.java:745)
2016-10-17 13:24:54,422	ERROR	java.util.concurrent.ThreadPoolExecutor$Worker	Unable to save result data
java.lang.RuntimeException: Unable to save result data
	at ca.bc.gov.open.cpf.api.scheduler.BatchJobService.newBatchJobResult(BatchJobService.java:911)
	at ca.bc.gov.open.cpf.api.scheduler.JobPreProcessTask.addJobValidationError(JobPreProcessTask.java:117)
	at ca.bc.gov.open.cpf.api.scheduler.JobPreProcessTask.process(JobPreProcessTask.java:295)
	at ca.bc.gov.open.cpf.api.scheduler.BatchJobService.preProcessBatchJob(BatchJobService.java:1228)
	at ca.bc.gov.open.cpf.api.scheduler.BatchJobPreProcess.processJob(BatchJobPreProcess.java:53)
	at ca.bc.gov.open.cpf.api.scheduler.AbstractBatchJobChannelProcess.lambda$schedule$0(AbstractBatchJobChannelProcess.java:191)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at com.revolsys.logging.LoggingRunnable.run(LoggingRunnable.java:13)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Unable to create file
	at ca.bc.gov.open.cpf.api.web.controller.DatabaseJobController.newJobFile(DatabaseJobController.java:183)
	at ca.bc.gov.open.cpf.api.web.controller.AbstractJobController.setJobResult(AbstractJobController.java:147)
	at ca.bc.gov.open.cpf.api.scheduler.BatchJobService.newBatchJobResult(BatchJobService.java:908)
	... 9 more
Caused by: org.springframework.dao.DataIntegrityViolationException: Process Batch; SQL [BEGIN insert  into CPF.CPF_BATCH_JOB_FILES (BATCH_JOB_ID, FILE_TYPE, SEQUENCE_NUMBER, CONTENT_TYPE, DATA, WHEN_CREATED) VALUES (?, ?, ?, ?, ?, ?);END;]; ORA-01400: cannot insert NULL into ("CPF"."CPF_BATCH_JOB_FILES"."DATA")
ORA-06512: at line 1
; nested exception is java.sql.SQLIntegrityConstraintViolationException: ORA-01400: cannot insert NULL into ("CPF"."CPF_BATCH_JOB_FILES"."DATA")
ORA-06512: at line 1

	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:243)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)
	at com.revolsys.jdbc.JdbcConnection.getException(JdbcConnection.java:180)
	at com.revolsys.jdbc.io.JdbcWriterImpl.processCurrentBatch(JdbcWriterImpl.java:580)
	at com.revolsys.jdbc.io.JdbcWriterImpl.insert(JdbcWriterImpl.java:512)
	at com.revolsys.jdbc.io.JdbcWriterImpl.insert(JdbcWriterImpl.java:475)
	at com.revolsys.jdbc.io.JdbcWriterImpl.write(JdbcWriterImpl.java:692)
	at com.revolsys.jdbc.io.JdbcWriterImpl.write(JdbcWriterImpl.java:33)
	at com.revolsys.jdbc.io.JdbcWriterWrapper.write(JdbcWriterWrapper.java:67)
	at com.revolsys.jdbc.io.JdbcWriterWrapper.write(JdbcWriterWrapper.java:7)
	at ca.bc.gov.open.cpf.api.domain.CpfDataAccessObject.write(CpfDataAccessObject.java:938)
	at ca.bc.gov.open.cpf.api.domain.CpfDataAccessObject.write(CpfDataAccessObject.java:910)
	at ca.bc.gov.open.cpf.api.web.controller.DatabaseJobController.newJobFile(DatabaseJobController.java:181)
	... 11 more
Caused by: java.sql.SQLIntegrityConstraintViolationException: ORA-01400: cannot insert NULL into ("CPF"."CPF_BATCH_JOB_FILES"."DATA")
ORA-06512: at line 1

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:445)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:396)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:879)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:450)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:192)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:531)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:207)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:1044)
	at oracle.jdbc.driver.OraclePreparedStatement.executeForRowsWithTimeout(OraclePreparedStatement.java:10143)
	at oracle.jdbc.driver.OraclePreparedStatement.executeBatch(OraclePreparedStatement.java:10249)
	at oracle.jdbc.driver.OracleStatementWrapper.executeBatch(OracleStatementWrapper.java:230)
	at org.apache.commons.dbcp2.DelegatingStatement.executeBatch(DelegatingStatement.java:345)
	at org.apache.commons.dbcp2.DelegatingStatement.executeBatch(DelegatingStatement.java:345)
	at com.revolsys.jdbc.io.JdbcWriterImpl.processCurrentBatch(JdbcWriterImpl.java:578)
	... 20 more

**Comment by pauldaustin** [comment]
The CSV file does not conform to the CSV specification. Values must be enclosed in "" if they contain a comma. The value [STREET_NAME.missing:10,STREET_TYPE.missing:6].

Was this file generated by CPF, BGEO (standalone) or manually created.

There is 1 CPF bug.

Because of the invalid CSV the parcelPoint has a value of F which is not a valid WKT geometry. This causes an exception to be thrown.

The CPF is then not marking the job as failed with invalid input data which it should do.

**Comment by mraross** [comment]
I did create this by hand and yes, it is invalid. CPF just needs to handle this type of invalidity more gracefully as you suggest.

**Comment by mraross** [comment]
Can you reliably detect when there are more or less data fields than declared in row 1? If the next field happen to be the correct type, CPF would never know there was anything wrong with the row.

**Comment by pauldaustin** [comment]
Added code to catch individual field errors in CSV files and report those on a record by record basis.

Added code to catch any other errors and fail the whole job

**Comment by mraross** [comment]
Looking good on dev

**Comment by mraross** [comment]
Latest deployment on delivery now causes batch job to hang

**Comment by pauldaustin** [comment]
details job id etc?

Paul Austin
President/CEO
Revolution Systems Inc.

+1 (604) 288-4304
paul.austin@revolsys.com
www.revolsys.com

**Comment by mraross** [comment]
jobs 6634 and 6635. Feel free to submit a new job with the CSV file I emailed you.

**Comment by pauldaustin** [comment]
This was caused be a new issue exposed in recent changes. The code was updating the status to 'processed' in database when pre-processing had the same number of requests as errors. It then sent it straight to the pre-processor. That code hadn't been updated to also update the in-memory cached version of the job. So although the database had it as processed the post-processor ignored it as it thought the status was creating requests.

**Comment by mraross** [comment]
Verified in prod
